version: "3.9"
networks:
  mongo:
    driver: bridge
services:
  server:
    build: ./server
    ports:
      - "80:5000"
    volumes:
      - ./server:/app
    environment:
      FLASK_DEBUG: development
  web:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/user/src/app
    depends_on:
      - server
  db:
    image: mongo:latest
    container_name: mongodb
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=cryptocurrency_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./engine/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    networks:
      - mongo
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      #- ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      #- ME_CONFIG_BASICAUTH_USERNAME=root
      #- ME_CONFIG_BASICAUTH_PASSWORD=pass
    #volumes:
      #- $HOME/uzrnem/database/mongo_db
    ports:
      - 8002:8081
    networks:
      - mongo
    depends_on:
      - db